language: node_js

node_js:
  - 12.18.1

branches:
  only:
    - master
    - /^KH-\d*-*/

jobs:
  include:
    - name: "Jest + Enzyme Tests"
      script:
        - yarn install
        - yarn test

#before_install:
#  - openssl aes-256-cbc -K $encrypted_01ee5a5a4535_key -iv $encrypted_01ee5a5a4535_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
#  - openssl aes-256-cbc -K $encrypted_934ea3bc4877_key -iv $encrypted_934ea3bc4877_iv -in id_rsa.pub.enc -out ~/.ssh/id_rsa.pub -d
#  - eval "$(ssh-agent -s)"
#  - chmod 600 ~/.ssh/id_rsa
#  - chmod 600 ~/.ssh/id_rsa.pub
#  - ssh-add ~/.ssh/id_rsa

#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: bash ./deploy.sh
#    on:
#      branch: master
